### ISSUE TITLE
protocol rtsp not supported

### ISSUE THREAD

**Issue by daiv87** [motioneye-project/motioneye#2546]
hello everybody!

i'm trying to installer motion-eye in qnap TS231 P3 whith docker-compose.
```
version: "3.5"
services:
  motioneye:
    image: ccrisan/motioneye:master-armhf  
    ports:
      # - "9001:9001"
       - "8765:8765"
    volumes:
    - "/share/domotica/config/motion-eye/localtime:/etc/localtime:ro"
    - "/share/domotica/config/motion-eye/etc:/etc/motioneye"
    - "share/domotica/config/motion-eye/lib:/var/lib/motioneye"

and when i insert the RTSP addressmotion
![Screenshot from 2022-06-29 14-12-55](https://user-images.githubusercontent.com/50885323/176435975-2894b222-f711-4dea-990c-b60df0d21fe6.png)

this is the log 
 
```
ERROR: ffmpeg: could find version: Command '/usr/bin/ffmpeg -version' returned non-zero exit status 127
/usr/bin/ffmpeg: error while loading shared libraries: libudev.so.1: ELF load command alignment not page-aligned
```
thanks to who will answer me
