### ISSUE TITLE
Streaming URL doesn't work

### ISSUE THREAD

**Issue by Tamas92** [motioneye-project/motioneye#2769]
I'm running the motioneye via docker compose. Everything works fine except the streaming URL. If I go to the http://myip:8081 it shows nothing. (This site can't be reached) Everything else is working, snapshot url etc.  I checked the netstat -tulpn | grep 8081, no output unfortunately. What can be the problem?

**Comment by MichaIng** [comment]
Where did you pull the container from? Obviously that `motion` port needs to passed between container and host via `docker run` argument or Docker Compose YAML.

**Comment by Tamas92** [comment]
I'm using the ccrisan/motioneye:master-amd64. 

Anyway here is my docker compose file:

```
version: "3"
services:
  motioneye:
    image: ccrisan/motioneye:master-amd64
    container_name: motioneye
    restart: always
    user: root
    ports:
      - 8765:8765
      - 8081:8081
    devices:
      - /dev/video2:/dev/video2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc:/etc/motioneye
      - ./lib:/var/lib/motioneye
      - ./var/run/motion:/var/run/motion
```
