### ISSUE TITLE
Clearing up moves sooner than 1 day

### ISSUE THREAD

**Issue by sts-ryan-holton** [motioneye-project/motioneye#3089]
I've just installed Motioneye via Docker on Raspberry Pi 5 via the following docker compose file. My SD card is only 32GB and I only want to upload my recordings to my Synology NAS. I don't need them on the Pi. Since there's no option to set Network Share because it relies on additional packages and root user, I've turned on the Upload Service which is working, however, there's no point keeping media files on the pi beyond say 15 mins. Can i set Preserve Movies to custom and set a float for movies lifetime, for instance, 0.005 or something? What is this value?

```yml
services:
  motioneye:
    image: ghcr.io/motioneye-project/motioneye:edge
    container_name: motioneye
    ports:
      - "8765:8765"
      - "9081:9081"
    volumes:
      - ./motioneye:/etc/motioneye
      - /etc/localtime:/etc/localtime:ro
      - /data/motioneye:/var/lib/motioneye
    devices:
      - /dev/video0:/dev/video0
    restart: unless-stopped
```
